### PR TITLE
Ci

### PR DESCRIPTION
**Pull request by aremazeilles**
Do mot merge before #9 

If well done, it should, at each PR or push to the master branch, generate the docker image and test given the input and output provided.

Tests are not launched for `fpe`as we do not have the reference output file (see #6).
Before pulling, would like also to adjust input file name (wait for #7 maybe)

### CODE REVIEW

**Comment by aremazeilles** [comment]
hang on, I need to solve that conflict, I'll tell you when I have it done.

**Comment by aremazeilles** [comment]
Adding the CI process (which automatically verifies that the output files are obtained when the scripts are called with the test input file). 
I moved output files into folder per script, and added test as well for fpe. 
But I have an issue with the output of  fpw, as some files generated differ from the one stored:

Screenshot from 2020-10-13 11-54-44
In blue, the files that differ.

Looking at pi_FPE_ap.yaml:

Generated:
```
type: 'vector'
values: 
0.13004
0.15935
0.18911
0.20668
0.24007
``` 

stored:
```
type: 'vector'
values: 
0.11568
0.15772
0.18137
0.20197
0.23105
```

pi_FPE_ml.yaml: generated start with 0.10977, while the stored one starts with 0.11002
pi_l_MOS_ap.yaml: generated start with -0.22490, while the stored one starts with -0.29898
pi_r_MOS_ap.yaml: generated start with -0.14876, while the stored one starts with -0.32304 

**Without uploading any files to the git** could you check, by calling the `fpe` program, whether you get results like me, or like the ones stored into the git folder?

Thanks

**Comment by nickkluft** [comment]
All generated ones are correct.

**Comment by aremazeilles** [comment]
OK, so I can replace the ones stored with the ones generated, do you agree?

**Comment by nickkluft** [comment]
Yes!

**Comment by aremazeilles** [comment]
So the check is now ok, I think this can be merged now

**Pull request merged**
