### PR TITLE
Fix yaml

### PR DESCRIPTION
**Pull request by nickkluft**
All yaml issues fixed. As one of the input needed adjustments, the getevents functions needed to be adjusted too. I ran the yamllint on the inputs and outputs and it did not result into errors. However, it might be good to check wheter the gaitEvents.yaml has the expected structure.

### CODE REVIEW

**Comment by aremazeilles** [comment]
The CI process is detecting an issue. This might be because the reference output file has not been updated.
I will check it and get back to you.

**Comment by aremazeilles** [comment]
To See the CI process, Click on Details on the area stating "All checks have failed"

**Comment by aremazeilles** [comment]
It seems that you are working on it right now.
Can you ping me when you are done? An inportant point is to make sure that launching the command as indicated in the README, (run_fpe, run_fpm, ...) the output files generated (in the out_tests folder, to be created locally) are equal to the ones stored in tests/data/output. If they are different, you have to decide whether the reference output has to be updated, or whether your introduced a bug in your program. That is the purpose of the reference data.
To compare folders, under linux I use meld. Winmerge under windows.

The latest fpe/pi_FPE_ap.yaml must be wrong. It contains only nan values.

**Comment by aremazeilles** [comment]
The CI process still complains, which means that computing your metrics on the input data, we do not get the output pi as they are stored in `tests/data/output`.
For instance, launching:
```
run_fpe tests/data/input/subject_04_cond_23_run_01_jointTrajectories.csv tests/data/input/subject_04_cond_23_run_01_com.csv tests/data/input/subject_04_cond_23_run_01_angularMomentum.csv tests/data/input/subject_04_cond_23_run_01_inertiaTensor.csv tests/data/input/subject_04_cond_23_run_01_gaitEvents.yaml tests/data/input/cond_23_testbed.yaml out_tests
```
 The generated `out_tests/pi_FPE_ap.yaml` starts with:
```yaml
---
type: 'vector'
values:
 0.08415
 0.08210
 0.02099
 -0.05143
 0.01049
 0.01488
 0.00281
 0.01577
```
while the stored file `tests/data/output/fpe/pi_FPE_ap.yaml ` starts with:
```
---
type: 'vector'
values:
 -0.36345
 -0.31638
 -0.48273
 -0.29019
 -0.46197
 -0.34921
 -0.17858
 0.06917
 0.31700
 0.29841
```
Two options: (i) the computation is wrong, (ii) the reference data needs to be updated.

**Comment by aremazeilles** [comment]
ping

**Comment by nickkluft** [comment]
@aremazeilles, the input files and associated output files are now updated. The issue was that the inertial tensor was incorrectly defined in one of the input files. It took me longer to fix this than expected. My apologies.

**Comment by aremazeilles** [comment]
Thanks the CI is happy, so I think it is a good sign. I'll revise this on Monday. Have a good week end!

**Pull request merged**
